---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: 793d05316077345337ae9a11ae05ec8f23edfe1b  # frozen: v2.14.0
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint-fmt
      - id: golangci-lint-full
